spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.200.124:3306/movie_booking_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: TJL
    password: '041024'
  mvc:
    format:
      date: yyyy-MM-dd
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  servlet:
    encoding:
      charset: utf-8
  port: 8888

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JWT配置
jwt:
  secret: movie-booking-system-secret-key-2024
  expiration: 86400

# 文件上传配置
file-upload-path: ./uploads

logging:
  level:
    com.example.movie_booking_backend: debug
    org.springframework.security: debug